name: placeholder
description: Display placeholder before rendering in Flutter.
version: 0.0.1
author: Jin Liu <coolziljin@gmail.com>
homepage: https://github.com/coolzilj/flutter_placeholder

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
